### ISSUE TITLE
CIMTableView.FrozenFields is incorrect

### ISSUE THREAD

**Issue by kirkktx** [Esri/cim-spec#10]
It says:
_"The index of the frozen field."_
It should say:
_"The number of frozen fields"_
(More than one field can be frozen.)

ArcGIS Pro appears to reorder the fieldDescriptions array when a field is frozen.

**Comment by williamscraigm** [comment]
Fixed with this commit https://github.com/Esri/cim-spec/commit/544f474f911129292f80cba497eb33d88c6afd4a
