### ISSUE TITLE
CIMDisplayTableDefinition should be CIMDisplayTable

### ISSUE THREAD

**Issue by kirkktx** [Esri/cim-spec#11]
The Pro SDK has no CIMDisplayTableDefinition class.
It does have a[ CIMDisplayTable class](https://pro.arcgis.com/en/pro-app/latest/sdk/api-reference/#topic1049.html) though.
https://github.com/Esri/cim-spec/blob/master/docs/v2/CIMVectorLayers.md#cimdisplaytabledefinition
https://github.com/Esri/cim-spec/blob/master/docs/v2/CIMVectorLayers.md#cimdisplaytabledefinition-1
https://github.com/Esri/cim-spec/blob/master/docs/v2/CIMVectorLayers.md#cimdisplaytabledefinition-2

(Also, this is not very [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself))

**Comment by williamscraigm** [comment]
The spec here is reflecting abstract concepts which don't always result in classes in the Pro .NET SDK. As noted in this section: https://github.com/Esri/cim-spec#how-this-specification-is-formatted there is a sense of inheritance that's not possible in JSON since JSON doesn't support inheritance.
