### ISSUE TITLE
cimdefinition anchor missing

### ISSUE THREAD

**Issue by kirkktx** [Esri/cim-spec#12]
layerDefinitions for [CIMLayerDocument](https://github.com/Esri/cim-spec/blob/master/docs/v2/CIMDocument.md#cimlayerdocument-1) should point to here:
https://github.com/Esri/cim-spec/blob/master/docs/v2/Types.md#definition

but it points to here:
https://github.com/Esri/cim-spec/blob/master/docs/v2/Types.md#cimdefinition
(anchor doesn't exist)

**Comment by williamscraigm** [comment]
Thanks for reporting, this was fixed with this commit: https://github.com/Esri/cim-spec/commit/6b0a8d96ceae731e836349dae3f473a36dcca1ca
