### ISSUE TITLE
When will CIMLineSymbol CIMObjectMarker3D, CIMglTFMarker3D be supported in 3D SceneViews

### ISSUE THREAD

**Issue by JackFanZhang** [Esri/cim-spec#18]
Hi, does ESRI has plan for supporting CIMLineSymbol CIMObjectMarker3D, CIMglTFMarker3D in 3D SceneViews? thanks

**Comment by williamscraigm** [comment]
You're referring to Web Scenes? CIMglTFMarker3D is the equivalent of the WebScene ObjectSymbol3DLayer with a referenced gltf model. See https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-ObjectSymbol3DLayer.html. ArcGIS Pro will convert to this type on sharing

CIMObjectMarker3D has been removed in ArcGIS Pro 3.0 and models in this format are converted to CIMglTFMarker3D as it supports the full functionality of CIMObjectMarker3D .

CIMLineSymbol (and the rest of the CIM symbol models) are not supported in WebScenes at this time but discussion continues.

**Comment by williamscraigm** [comment]
Closing as this is not a spec issue but a question about the implementation of the spec as answered above.
