### ISSUE TITLE
please add 'publishing-sharing' as a new search topic

### ISSUE THREAD

**Issue by jgravois** [Esri/cim-spec#4]
we are showcasing this awesome new open source specification on http://esri.github.io/ now. i couldn't think of a better category fit than 'publishing and sharing'.

if any repo admins here could add a <kbd>publishing sharing</kbd> as a new GitHub [topic](help.github.com/articles/about-topics) (along with any others from [this list](https://github.com/Esri/esri.github.io/blob/v2/src/data/search-topics.yml) that are a good fit), it'd be _most_ appreciated.

congrats on releasing this! 🎉

**Comment by williamscraigm** [comment]
Done
