### ISSUE TITLE
add CHANGELOG?

### ISSUE THREAD

**Issue by jgravois** [Esri/cim-spec#5]
have y'all already thought through how you'll communicate changes to the spec as it evolves over time?

**Comment by williamscraigm** [comment]
The plan is to document every class, member etc with the version added.

**Comment by jgravois** [comment]
> The plan is to document every class, member etc with the version added.

awesome. that works.

even without a CHANGELOG, i'd highly recommend utilizing git [tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging).
